# Generated by Django 4.0.5 on 2022-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Velocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('start_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('end_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('velocity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
