# Generated by Django 4.0.5 on 2022-06-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_velocity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Velocity',
        ),
    ]
